name: Terraform Apply upon Approval

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2

permissions:
  id-token: write
  contents: read

jobs:
  plan-after-merge:
    name: Terraform Plan (Post-Merge)
    runs-on: ubuntu-latest

    outputs:
      plan-status: ${{ steps.plan.outcome }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure/app-hello-basit-comet

      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -out=tfplan
          terraform show -no-color tfplan > plan.txt
        working-directory: infrastructure/app-hello-basit-comet

      - name: Upload Plan Output
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: |
            infrastructure/app-hello-basit-comet/plan.txt
            infrastructure/app-hello-basit-comet/tfplan

  apply-with-approval:
    name: Terraform Apply (Requires Manual Approval)
    needs: plan-after-merge
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Plan Artifact
        uses: actions/download-artifact@v4
        with:
          name: tfplan
          path: infrastructure/app-hello-basit-comet

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.5

      - name: Terraform Init
        run: terraform init
        working-directory: infrastructure/app-hello-basit-comet

      - name: Terraform Apply
        run: terraform apply -auto-approve tfplan
        working-directory: infrastructure/app-hello-basit-comet
